spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/backlog?createDatabaseIfNotExist=true}
spring.datasource.username=${DB_USER:root}
spring.datasource.password=${DB_PASSWORD:}
spring.jpa.hibernate.ddl-auto=update
tmdb.api.key=${TMDB_API_KEY}
tmdb.api.url=https://api.themoviedb.org/3
sentry.dsn=${SENTRY_DSN}
sentry.traces-sample-rate=1.0
sentry.environment=development
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.max-lifetime=60000
spring.datasource.hikari.minimum-idle=0
brevo.api.key=${BREVO_API_KEY}
spring.jpa.open-in-view=false
spring.ai.google.vertexai.gemini.api-key=${GEMINI_API_KEY}
spring.ai.google.vertexai.gemini.model=gemini-1.5-flash